const dailySeeds=["What ordinary thing secretly makes no sense?","What did a pet do that felt suspiciously human?","What is the weirdest rule at your job?","What do people pretend to understand?","What is something only RV owners know?","What tiny inconvenience makes you dramatically angry?","What did you believe as a child that now sounds ridiculous?","What happens every time you enter a grocery store?","What does your family do that would confuse a documentary crew?","What technology solves one problem and creates three more?"];
const smiles=["Write the joke only you could write.","Keep the truth. Trim the extra words.","A rough joke is still a joke growing.","The audience cannot meet the version you never practice.","Funny grows when you show up.","Your point of view is the part nobody else can copy."];
function refreshDashboard(){const savedIdeas=load("laughrina-ideas",[]),savedSets=load("laughrina-sets",[]),savedFavs=load("laughrina-favorites",[]);$("#dashIdeas").textContent=savedIdeas.length;$("#dashReady").textContent=savedIdeas.filter(x=>String(x.stage).includes("Stage Ready")||String(x.stage).includes("Keeper")).length;$("#dashSets").textContent=savedSets.length;$("#dashKeepers").textContent=savedFavs.length;}
function seedOfDay(){const day=Math.floor(Date.now()/86400000);return dailySeeds[day%dailySeeds.length]}
function updateWelcome(){const h=new Date().getHours();const greeting=h<12?"Good morning":h<18?"Good afternoon":"Good evening";$("#welcomeLine").textContent=`${greeting}. Every great comedian started with one small observation.`;$("#todaySmile").textContent=smiles[Math.floor(Date.now()/86400000)%smiles.length];$("#dailySeed").textContent=seedOfDay();}
function plantDailySeed(){switchTab("garden");$("#ideaObservation").value=seedOfDay();$("#ideaTitle").value="Today's comedy seed";$("#ideaObservation").focus();}
function jokeTextFromIdea(x){return [x.observation,x.setup,x.punchline].filter(Boolean).join("\n")}
function scoreBar(label,value,note){return `<div class="coach-score"><div><strong>${label}</strong><span>${value}/10</span></div><meter min="0" max="10" value="${value}"></meter><small>${note}</small></div>`}
function analyzeJoke(){const text=$("#coachJoke").value.trim();if(!text){$("#coachResults").innerHTML='<p class="empty-state">Give Laughrina a joke first—she cannot coach invisible material, despite several rumors.</p>';return}const words=text.split(/\s+/).length;const sentences=text.split(/[.!?]+/).filter(Boolean).length;const hasTurn=/but|then|until|except|instead|turns out|apparently|suddenly/i.test(text);const hasSpecific=/\b(my|our|yesterday|today|dog|cat|mom|dad|boss|RV|Walmart|phone|neighbor)\b/i.test(text);const clarity=Math.max(4,Math.min(9,10-Math.floor(Math.max(0,words-55)/12)));const setup=Math.max(4,Math.min(9,hasSpecific?8:6));const punch=Math.max(4,Math.min(9,hasTurn?8:5));const originality=Math.max(5,Math.min(9,hasSpecific?8:6));const stage=Math.round((clarity+setup+punch+originality)/4);let tips=[];if(words>55)tips.push("Try cutting the setup by one sentence. Reach the funny turn sooner.");if(!hasTurn)tips.push("Add a clear surprise: what did the audience expect, and what happened instead?");if(!hasSpecific)tips.push("Add one specific detail from your real life. Specific usually feels more original.");if(sentences<2)tips.push("Try separating the premise from the punchline so the audience can follow the turn.");if(!tips.length)tips.push("The structure is clear. Practice it aloud and listen for any word you can remove.");const verdict=stage>=8?"🔥 This feels close to stage ready.":stage>=6?"🌿 This has real potential—one more rewrite could sharpen the landing.":"🌱 Strong seed. Keep the premise and build a clearer surprise.";$("#coachResults").innerHTML=`<div class="coach-verdict"><h3>${verdict}</h3><p>Comedy is subjective, so this is structural coaching—not a promise about any audience.</p></div>${scoreBar("Clarity",clarity,"Can an audience follow it on the first listen?")}${scoreBar("Setup",setup,"Does the premise feel recognizable and specific?")}${scoreBar("Punchline",punch,"Is there a clear turn or surprise?")}${scoreBar("Original voice",originality,"Does it sound grounded in a real point of view?")}${scoreBar("Stage readiness",stage,"How prepared the structure feels for rehearsal.")}<div class="coach-tips"><h3>Laughrina's next rewrite</h3><ul>${tips.map(t=>`<li>${t}</li>`).join("")}</ul></div>`}
function useNewestGarden(){const saved=load("laughrina-ideas",[]);if(!saved.length){switchTab("garden");return}$("#coachJoke").value=jokeTextFromIdea(saved[0]);analyzeJoke()}
$("#useDailySeed").onclick=plantDailySeed;$("#coachAnalyze").onclick=analyzeJoke;$("#coachFromGarden").onclick=useNewestGarden;document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>switchTab(b.dataset.jump));document.addEventListener("click",()=>setTimeout(refreshDashboard,50));updateWelcome();refreshDashboard();