const dailySeeds=["What ordinary thing secretly makes no sense?","What did a pet do that felt suspiciously human?","What is the weirdest rule at your job?","What do people pretend to understand?","What is something only RV owners know?","What tiny inconvenience makes you dramatically angry?","What did you believe as a child that now sounds ridiculous?","What happens every time you enter a grocery store?","What does your family do that would confuse a documentary crew?","What technology solves one problem and creates three more?"];
const smiles=["Write the joke only you could write.","Keep the truth. Trim the extra words.","A rough joke is still a joke growing.","The audience cannot meet the version you never practice.","Funny grows when you show up.","Your point of view is the part nobody else can copy."];
function refreshDashboard(){const savedIdeas=load("laughrina-ideas",[]),savedSets=load("laughrina-sets",[]),savedFavs=load("laughrina-favorites",[]);$("#dashIdeas").textContent=savedIdeas.length;$("#dashReady").textContent=savedIdeas.filter(x=>String(x.stage).includes("Stage Ready")||String(x.stage).includes("Keeper")).length;$("#dashSets").textContent=savedSets.length;$("#dashKeepers").textContent=savedFavs.length;}
function seedOfDay(){const day=Math.floor(Date.now()/86400000);return dailySeeds[day%dailySeeds.length]}
function updateWelcome(){const h=new Date().getHours();const greeting=h<12?"Good morning":h<18?"Good afternoon":"Good evening";$("#welcomeLine").textContent=`${greeting}. Every great comedian started with one small observation.`;$("#todaySmile").textContent=smiles[Math.floor(Date.now()/86400000)%smiles.length];$("#dailySeed").textContent=seedOfDay();}
function plantDailySeed(){switchTab("garden");$("#ideaObservation").value=seedOfDay();$("#ideaTitle").value="Today's comedy seed";$("#ideaObservation").focus();}
function jokeTextFromIdea(x){return [x.observation,x.setup,x.punchline].filter(Boolean).join("\n")}
function scoreBar(label,value,note){return `<div class="coach-score"><div><strong>${label}</strong><span>${value}/10</span></div><meter min="0" max="10" value="${value}"></meter><small>${note}</small></div>`}
function analyzeJoke(){const text=$("#coachJoke").value.trim();if(!text){$("#coachResults").innerHTML='<p class="empty-state">Give Laughrina a joke first—she cannot coach invisible material, despite several rumors.</p>';return}const words=text.split(/\s+/).length;const sentences=text.split(/[.!?]+/).filter(Boolean).length;const hasTurn=/but|then|until|except|instead|turns out|apparently|suddenly/i.test(text);const hasSpecific=/\b(my|our|yesterday|today|dog|cat|mom|dad|boss|RV|Walmart|phone|neighbor)\b/i.test(text);const clarity=Math.max(4,Math.min(9,10-Math.floor(Math.max(0,words-55)/12)));const setup=Math.max(4,Math.min(9,hasSpecific?8:6));const punch=Math.max(4,Math.min(9,hasTurn?8:5));const originality=Math.max(5,Math.min(9,hasSpecific?8:6));const stage=Math.round((clarity+setup+punch+originality)/4);let tips=[];if(words>55)tips.push("Try cutting the setup by one sentence. Reach the funny turn sooner.");if(!hasTurn)tips.push("Add a clear surprise: what did the audience expect, and what happened instead?");if(!hasSpecific)tips.push("Add one specific detail from your real life. Specific usually feels more original.");if(sentences<2)tips.push("Try separating the premise from the punchline so the audience can follow the turn.");if(!tips.length)tips.push("The structure is clear. Practice it aloud and listen for any word you can remove.");const verdict=stage>=8?"🔥 This feels close to stage ready.":stage>=6?"🌿 This has real potential—one more rewrite could sharpen the landing.":"🌱 Strong seed. Keep the premise and build a clearer surprise.";$("#coachResults").innerHTML=`<div class="coach-verdict"><h3>${verdict}</h3><p>Comedy is subjective, so this is structural coaching—not a promise about any audience.</p></div>${scoreBar("Clarity",clarity,"Can an audience follow it on the first listen?")}${scoreBar("Setup",setup,"Does the premise feel recognizable and specific?")}${scoreBar("Punchline",punch,"Is there a clear turn or surprise?")}${scoreBar("Original voice",originality,"Does it sound grounded in a real point of view?")}${scoreBar("Stage readiness",stage,"How prepared the structure feels for rehearsal.")}<div class="coach-tips"><h3>Laughrina's next rewrite</h3><ul>${tips.map(t=>`<li>${t}</li>`).join("")}</ul></div>`}
function useNewestGarden(){const saved=load("laughrina-ideas",[]);if(!saved.length){switchTab("garden");return}$("#coachJoke").value=jokeTextFromIdea(saved[0]);analyzeJoke()}

function instructionBox(title,body,open=false){const box=document.createElement("details");box.className="how-it-works";box.open=open;box.innerHTML=`<summary>💡 ${title}</summary><p>${body}</p>`;return box}
function addInstructions(){
  const style=document.createElement("style");style.textContent=`
  .start-here{margin-top:22px}.start-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-top:14px}.start-step{border:1px solid var(--border);background:var(--surface2);border-radius:16px;padding:14px;text-align:center}.start-step span{display:block;font-size:1.65rem;margin-bottom:5px}.start-step strong{display:block;font-family:"Baloo 2"}.start-step small{color:var(--muted);line-height:1.35}.how-it-works{margin:14px 0 18px;border:1px solid rgba(112,241,194,.22);background:rgba(112,241,194,.07);border-radius:14px;padding:0 14px}.how-it-works summary{cursor:pointer;padding:12px 0;font-weight:800;color:var(--mint);list-style:none}.how-it-works summary::-webkit-details-marker{display:none}.how-it-works summary:after{content:"＋";float:right}.how-it-works[open] summary:after{content:"−"}.how-it-works p{margin:0 0 14px;color:var(--muted);line-height:1.55}.how-it-works strong{color:var(--text)}@media(max-width:760px){.start-steps{grid-template-columns:1fr 1fr}.start-step:last-child{grid-column:1/-1}}`;
  document.head.appendChild(style);
  const guide=document.createElement("section");guide.className="panel start-here";guide.innerHTML=`<p class="eyebrow">NEW HERE?</p><h2>Start Here: Your First Joke in Five Steps</h2><div class="start-steps"><div class="start-step"><span>🌱</span><strong>1. Plant</strong><small>Write one funny observation.</small></div><div class="start-step"><span>✍️</span><strong>2. Shape</strong><small>Add a setup and punchline.</small></div><div class="start-step"><span>🌟</span><strong>3. Coach</strong><small>Ask Laughrina for feedback.</small></div><div class="start-step"><span>🧩</span><strong>4. Build</strong><small>Add it to a set.</small></div><div class="start-step"><span>🎤</span><strong>5. Practice</strong><small>Perform it under the light.</small></div></div>`;
  document.querySelector(".daily-card").after(guide);
  const garden=document.querySelector("#garden .panel-heading");garden.after(instructionBox("How to use the Joke Garden","Start with a real moment or observation. Add only the details the audience needs in the setup, then finish with a surprising punchline. Save rough ideas too—seeds do not need to be perfect.",true));
  const sets=document.querySelector("#sets .panel-heading");sets.after(instructionBox("How to build a set","Add jokes from your Joke Garden, arrange them in performance order, and watch the estimated runtime. Start with something dependable, vary the rhythm in the middle, and place a strong closer last."));
  const practice=document.querySelector("#practice .panel-heading");practice.after(instructionBox("How to practice under The Light","Choose a time and press Start. Perform without stopping when you make a small mistake. Green means keep your rhythm, yellow means begin wrapping up, and red means land your closer."));
  const coach=document.querySelector("#coach .panel-heading");coach.after(instructionBox("How Would You Laugh? works","Paste the complete setup and punchline, or load your newest garden joke. Laughrina reviews clarity, setup length, specificity, and surprise. The feedback is a writing guide—not a guarantee of audience reaction."));
  const comedy=document.querySelector(".control-grid article:first-child .panel-heading");comedy.after(instructionBox("How to use Comedy Modes","Pick a style when you need inspiration, then tap Hit Me Again for another example. Save anything that sparks an idea, but rewrite it in your own voice before performing."));
  const roast=document.querySelector(".control-grid article:nth-child(2) h2");roast.after(instructionBox("How Gentle Fire works","Choose a heat level for a playful roast. Laughrina aims at habits, choices, awkward moments, and harmless nonsense—not identity, trauma, appearance, or vulnerabilities."));
}

$("#useDailySeed").onclick=plantDailySeed;$("#coachAnalyze").onclick=analyzeJoke;$("#coachFromGarden").onclick=useNewestGarden;document.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>switchTab(b.dataset.jump));document.addEventListener("click",()=>setTimeout(refreshDashboard,50));updateWelcome();refreshDashboard();addInstructions();